[package]
name = "catdisk"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = [ "full" ]}
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "sqlite" ] }
clap = { version = "4.5.20", features = ["derive"] }
